### ISSUE TITLE
Getting error when installing

### ISSUE THREAD

**Issue by CamelJohn** [artiebits/ngx-highlight-words#37]
**Describe the bug**
getting `npm ERR!` when installing the lib.
tried using the `--legacy-peer-deps` flag. it still results in the same error.

**To Reproduce**
1. create new angular project with angular cli (v13.0.1).
2. run `npm install ngx-highlight-words`.

**Expected behavior**
the lib should install without errors - meaning it should be compatible with angular 13.

**Screenshots**
![image](https://user-images.githubusercontent.com/47652778/150301195-0118d949-9806-4f76-9b17-29e07321fea7.png)

**Desktop OS:**
 - mac big Sur

**Comment by artiebits** [comment]
Hi, thank you for reporting the issue, I will take a look!

**Comment by artiebits** [comment]
I've tried to create a new Angular app using [Angular CLI](https://angular.io/cli) v13.1.3, then successfully installed the `ngx-highlight-words` package. Could you try `rm -rf node_modules`, then `npm install`, and then `npm install ngx-highlight-words`. Thank you

**Comment by artiebits** [comment]
Hi @CamelJohn, do you still experience the issue?
